name: Discussion Autoresponder

on:
  discussion:
    types: [created]

jobs:
  autorespond:
    name: Posts an autoresponder comment on a new discussion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Discussion Autoresponder
        id: autorespond
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Show Output
        run: |
          echo "discussionId = ${{ steps.autorespond.outputs.discussionId }}"
          echo "commentId = ${{ steps.autorespond.outputs.commentId }}"
          echo "commentBody = ${{ steps.autorespond.outputs.commentBody }}"
          echo "clientMutationId = ${{ steps.autorespond.outputs.clientMutationId }}"