name: Discussion Autoresponder

on:
  discussion:
    types: [created]

jobs:
  autorespond:
    name: Posts an autoresponder comment on a new discussion
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}